global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: shape-tree-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:42068"]
        labels:
          service: shape-tree-api

  - job_name: shape-tree-web
    metrics_path: /metrics
    static_configs:
      - targets: ["web:42070"]
        labels:
          service: shape-tree-web
