/// ShapeTree API client generated by `swift-openapi-generator`.
///
/// The `Client` struct (transport-agnostic) and request/response types are
/// auto-generated at build time from the bundled `openapi.yaml`.
///
/// ## Quick start (local server on :42069)
/// ```swift
/// import OpenAPIAsyncHTTPClient
/// import ShapeTreeClient
///
/// let transport = AsyncHTTPClientTransport()
/// let client = Client(
///     serverURL: try Servers.Server1.url(),
///     transport: transport
/// )
/// let response = try await client.createSession()
/// let sessionId = try response.ok.body.json.id
///
/// let completion = try await client.runCompletion(
///     path: .init(id: sessionId),
///     body: .json(.init(message: "Hello!"))
/// )
/// print(try completion.ok.body.json.assistant)
/// ```
